#!/bin/bash
read -p "Enter the SQL file name: " sql_file

if [ -f "$sql_file" ]; then
	read -s -p "Enter MySQL password: " mysql_password
	echo

	cat "$sql_file" | mysql -hlocalhost -uroot -p"$mysql_password"
else
	echo "Error"
fi
